#!/bin/bash
cd /home/duncan/UChicago/MuonBeam/muonphillic/Processes/m1/Feynman/w
nice -n 19 ln -s ../p1/results results  2>&1 1>  job.o
err=$?
if(test $err -ne 0) then
	echo CH Error $err
fi
echo n_calchep is created
touch finished-symbolic
