#!/bin/bash
cd /home/duncan/UChicago/MuonBeam/muonphillic/Processes/m1/Feynman/p1
nice -n 19 ./calchep -blind "5[[[{1{}{{mu-,N0->mu-,S0,N0{{[{[[[{"  2>&1 1>  job.o
err=$?
if(test $err -ne 0) then
	echo CH Error $err
fi
touch finished-symbolic
